### ISSUE TITLE
Documentation: Output on Memory page is misleading

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-python-stix2#107]
This is the output from a loop printing the results of a query - but they look "different"

{'name': 'Urban2', 'created': '2017-09-12T13:26:18.023Z', 'labels': ['rootkit'], 'modified': '2017-09-12T13:26:18.023Z', 'type': 'malware', 'id': 'malware--2daa14d6-cbf3-4308-bb8e-226d324a08e4'}

{
"type": "malware",
"id": "malware--2b3dd412-18a5-4e81-8742-4977068eb3eb",
"created": "2017-09-29T19:52:17.028Z",
"modified": "2017-09-29T19:52:17.028Z",
"name": "Alexios",
"labels": [
"rootkit"
]
}

**Comment by mbastian1135** [comment]
Did you see the code comment explaining why the output is different? 

In code comment:
    # note that python STIX objects are pretty-printed
    # due to some python dunder method magic, but normal
    # python dictionaries are not by default. Thus the
    # python STIX objects and python STIX dictionaries
    # that match the above query can be easily identified visually

**Comment by rpiazza** [comment]
No - of course not :-(

But it seems strange that the contents of the "memory" data store would contain "different" kinds of python objects - can we make sure everything is a STIX object?

**Comment by gtback** [comment]
@rpiazza : We've talked about this and gone back and forth. Ultimately, converting "normal" dicts to python-stix2 objects is troublesome because of the potential for custom properties, and converting python-stix2 objects to dictionaries negates most of the benefits of python-stix2. 

Our attitude has generally been "if you store dictionaries, you'll get back dictionaries; if you store python-stix2 objects, you'll get those back". `load_from_file()` should parse into python-stix2 objects by default, but it seems like it doesn't do that right now.

I don't think the guide needs to go into a ton of detail, but the examples should generally use STIX objects, with maybe a note at the bottom saying something to the effect of "if you store normal dictionaries, we won't modify them unless you write them to a file and later read that file back".

**Comment by mbastian1135** [comment]
Ill attempt to rewrite the sections and examples a little to be more explicit.
