### ISSUE TITLE
TAXIICollectionSource should capture HTTP errors

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-python-stix2#113]
Wrap calls to `get_object` and `get_objects`, catch an HTTP 404 or other errors, and return `None` or an empty list as appropriate.

**Comment by gtback** [comment]
Yep, it looks like it got done. Thinking about this more, though, do we really want to return an empty list for *any* HTTP error? I can understand for a 404, but if the authentication is bad (401, 403), or there's a problem on the server (5xx), do we want to alert the user to that somehow?

**Comment by gtback** [comment]
I'm not sure what you mean by "Graceful API warning response", but I agree that it probably wouldn't be my first choice.

On one hand I don't want to introduce a bunch of custom exceptions, but on the other hand I don't think returning HTTPErrors from requests is the best option either. On the third (?) hand, maybe this is something best handled in the taxii-client, rather than just calling `raise_for_status()` there ([1](https://github.com/oasis-open/cti-taxii-client/blob/573ec9ac5a0aa2432d23683afed96b1463d535f6/taxii2client/__init__.py#L808), [2](https://github.com/oasis-open/cti-taxii-client/blob/573ec9ac5a0aa2432d23683afed96b1463d535f6/taxii2client/__init__.py#L825)).

I'm open to suggestions. @emmanvg  @clenk do you have ideas?

**Comment by chisholm** [comment]
In general, I am okay with returning a special value (e.g. None or empty list) which indicates not-found, instead of raising an exception.  Especially if these not-found conditions are routine and normal, as it can make caller code simpler.  But the spec looks like it defines 404 as meaning either not-found, or access-denied, which makes it ambiguous.  The spec keeps saying for 404s: "... does not exist or the client does not have access ...".  And I wouldn't want to confuse an access-denied error with a not-found error.

Perhaps what the spec intended was to say that it is legal for a TAXII server to make it appear to clients *as if* the requested resource does not exist, when the client doesn't have permission to access it.  The client is still intended to interpret 404's as not-found, in which case the status is effectively unambiguous from the client's point of view.

Would an exception which indicates a 404 status occurred, carry any substantively different information, than an empty list or None, which was documented to mean that the requested resource was not found?

For other types of errors, I think exceptions make sense.  But it sounds like Greg is uncomfortable with passing Requests' `HTTPError` through to higher level software layers.  I think it is probably okay for taxii-client to raise HTTPError.  But python-stix2 is designed around more abstract sources/sinks, and users may use different sources and sinks or combinations of them, and one could argue that the source/sink interfaces should be defined with consistent predictable exception types.  Users shouldn't have to guess at what exceptions a source or sink might throw.  Maybe some higher-level exception classes are called for; the lower-level exceptions (e.g. network, disk I/O, etc) could be retained as the "cause" of the higher-level exceptions?

**Comment by johnwunder** [comment]
Sorry for the other duplicate report, I thought I searched for "error" but apparently not.

I can tell you as a user, it was very confusing to me when I made a request, in particular with a filter, and the response was an empty list. It took me awhile to track back from the collection being empty, to maybe the filter is wrong, to I just had the wrong URL. Returning None would let me differentiate between an empty set (filtered everything out, collection is empty) and a mis-typed URL...raising an error would also work.

In the TAXII spec, you're right that the intent of the spec was that in cases where the client was unauthorized you could either explicitly say that via the unauthorized status or you could just pretend it didn't exist to avoid giving away info about what collections exist or don't by calling it not found.

**Comment by gtback** [comment]
I'm OK with TAXII servers that return a 404 when they want to pretend that a resource doesn't exist. GitHub does that for private repos and other URLs. 

I think I was a bit too ambitious with the original description. For a 404 error on `/objects/<guid>`, I think returning None makes sense. If `/objects` returns an error (for query/get_objects), we should probably raise an exception. If `query` returns no results, then return an empty list. We may want to check some of the required metadata for a Collection passed into TAXIICollectionDataSource, to see if the Collection URL is valid (for the provided name/password), and then raise an error even before the call to query.

**Comment by mbastian1135** [comment]
So, summarizing:
 - get() | get_object() | /objects/<guid> -> return None on 404 bc either way user cannot get object
 - query()/all_version() | get_objects() | /objects -> return errors as exceptions, return [] if no results

- @Greg, youre proposing to check the supplied collection instance to see if its valid? Shouldnt that be an initialization (or lazy) check within the TAXII Client, not in the DataSource.  If not, would calling Collection.refresh() (https://github.com/oasis-open/cti-taxii-client/blob/master/taxii2client/__init__.py#L432) suffice?

**Comment by gtback** [comment]
I think that's right for the error conditions. Does that seem reasonable?

Because `Collection` loads its attributes lazily, you can construct a `TAXIICollectionSource`, pass in a `Collection` and not realize it's a non-existent URL until you call `get` or `query`, which seems non-intuitive. We can call `refresh()`, but it might be more straightforward to check `can_read` of the `Collection` in `TAXIICollectionSource.__init__` and `can_write` in `TAXIICollectionSink.__init__`, which will detect the 404 as well as the permission error.

**Comment by gtback** [comment]
Closed by #181
