### ISSUE TITLE
Allow dictionaries as filter values

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-python-stix2#139]
Bug: Cant pass a dictionary as a filter value. Came back with some sort of set not hashable error. We came up with a solution that basically tries to create a set() of filters (to optimize and remove unnecessary duplicate filters), but if that fails (due to unhashable types like list or dict), to not worry about it.

**Comment by mbastian1135** [comment]
So looking into this I see two options:
- We convert to using lists as our internal structure for maintaining filters (instead of sets).  This doesnt seem to be problematic as we only use sets because it made sense to, in order to have unique groups of filters; i.e. no downstream effects. This would also point us towards a  "FilterSet" like object because we do a lot of adding filters to groups of filters; or at least an "add_and_update_filters()" internal utility.

OR

- Convert  dicts to nested (named) tuples when a created Filter has a dict as a value. This seems cumbersome but would maintain current Filter structure (I think)

Thoughts? @gtback @clenk

**Comment by chisholm** [comment]
The first bullet is basically to deduplicate in a different way (other than throwing stuff into sets and let the hash functions take care of it).  This could done by keeping lists and deduplicating via a function call, or encapsulating the whole thing in a new FilterSet class which auto-dedupes as filters are added.  Second bullet is to "unpack" the dicts into sets of simple dotted property tests (such that values are immutable/hashable).  That'll work too, and also have the side effect of more effective deduping: a dotted property test with a simple value could be redundant with an undotted property test with a dict value.  A simple equality check on prop/op/value wouldn't catch this.

Here are some more ideas:
* define `__hash__` and `__eq__` on the Filter class, making it hashable.  Then you're on the honor system for not changing the filter after it has been inserted into a set.  You'll have to write your own algorithm for hashing dicts.  You could also write one for lists, and remove the auto-conversion hack.
* get an immutable hashable dict implementation to use, e.g. [dictionaries](https://pypi.python.org/pypi/dictionaries/0.0.1).  Then you can add an auto-conversion hack for dicts just like the one for lists.

Throwing another idea out there: there is more to redundancy than prop/op/value equality.  E.g. ("foo", ">", 1) and ("foo", ">", 2) are technically redundant: since they're implicitly AND'd, they're equivalent to just ("foo", ">", 2).  So you could drop the first filter.  You probably don't want this much sophistication, but just sayin'... :)

**Comment by gtback** [comment]
Thanks for the suggestions, @chisholm and @mbastian1135.

If I remember correctly, a major motivation behind deduplication is for composite data sources, where the parent data source and child data source may have identical default filters, and not wanting duplicate URL parameters in TAXII queries, for instance. We are not as worried about trying to catch people accidentally adding the same filter twice. Either way, it doesn't really hurt to have duplicate filters other than the slight inefficiency.

My gut feeling is to just **store filters in a list**, and (maybe) consider deduplicating the list right before it gets used. The default built-in implementation of `__eq__` should work fine for this, and we don't need to worry about implementing our own `__hash__`.

The "unpacking" of dicts would be an interesting challenge, but I worry it may run into the same problems that are leading us to want some `s` index for lists in STIX pattern (when you want all properties to match the *same* element of a list, rather than each matching *any* item of the list). 

The "semantic" deduplication of redundant filters is also an interesting challenge, but probably not worth the complexity right now.

**Comment by gtback** [comment]
@mbastian1135 , @clenk Can this be closed now that #166 was merged?

**Comment by clenk** [comment]
Yep.
