### ISSUE TITLE
Allow generic custom objects for Cyber Observables

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-python-stix2#157]
The recent changes made to the library allows parsing generic custom objects, but `parse_observable()` does not have the feature implemented.
https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/v20/observables.py#L903 
It also looks like we are **not** using `allow_custom` when we call it.
https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/v20/observables.py#L36

**Comment by clenk** [comment]
I started work on this: https://github.com/oasis-open/cti-python-stix2/commit/b633fd37856ccd15257d7d6bae3223411a90e9ef

However, parsing fails even with `allow_custom=True` when parsing an Observed-Data object that contains a custom observable object, or parsing an observable object with a custom extension because `_check_property` has no knowledge of the `allow_custom` value that was provided when the parent object was created. I'm hesitant to add `allow_custom` to every object type; is there another way to get around this?

**Comment by gtback** [comment]
Random thought (might be crazy):

Maybe we're thinking about this backwards (specifically in `ObservedData` and `_Observable`, but also throughout the library). What if we *always* allow custom properties and types, but just set a flag (like `_has_custom`) on STIXBase objects that contain custom properties. Then we can check if that flag is True once the constructor returns, and raise an error or not based on whether `allow_custom` is True). Does that make sense? Does it sound crazy?

**Comment by clenk** [comment]
When you allow a custom SDO type, it gets returned as a python dictionary, not a `_STIXBase` object. So having a `self.__has_custom` in `_STIXBase` wouldn't work in those cases. We could create a `GenericCustomObject` class that subclasses STIXBase and overwrite methods like `clean` and `_check_property`, but that gets a little more complicated (and won't make it into a 1.0 release).
