### ISSUE TITLE
Create an Extension with Dict annidate inside List

### ISSUE THREAD

**Issue by oliveriandrea** [oasis-open/cti-python-stix2#161]
Hi,
I'm trying to create a CyberObservable Extension for UserAccount which have to contain a DictionaryProperty() inside a ListProperty(). It is possible? Because when I try to create an extension like this one

```
@CustomExtension(UserAccount, 'ssh_keys', {
   keys': ListProperty(DictionaryProperty(), required=True)
 })
 class SSHKeysExtension:
     pass
```

and use it with example = SSHKeysExtension(keys=[{'test123':123, 'test345','aaaa'}])
I obtain a lot of strange errors (the library seems to interpreter the dict as parameters for __init__()

**Comment by gtback** [comment]
Thanks, @oliveriandrea. I know we've been making some changes lately to how custom objects and extensions work. Are you using the master version from GitHub, or a version released on PyPI?

@clenk do you have any ideas?

**Comment by oliveriandrea** [comment]
Im using the PIP version of the library

**Comment by clenk** [comment]
Looks like this is a bug; I got the same results and am working on a fix.

I also found another problem when trying to print the custom extension because of a bug in [find_property_index](https://github.com/oasis-open/cti-python-stix2/blob/master/stix2/utils.py#L166) in which no value was being returned.

I'll get these fixed soon.

**Comment by oliveriandrea** [comment]
When you think a new release of the library will be available in order to install it (with this patch) using PIP?

**Comment by gtback** [comment]
@oliveriandrea We will be releasing 1.0.0 today.
