### ISSUE TITLE
Infinite recursion on _STIXBase object deserialization

### ISSUE THREAD

**Issue by stbe** [oasis-open/cti-python-stix2#186]
Hi!

There seems to be a bug in the way the `__getitem__`/`__getattr__` functions are implemented in `_STIXBase` (_cti-python-stix2/stix2/base.py_). The bug can be reproduced by trying to serialize/deserialize an object instance, resulting in infinite recursion causing the program to terminate with a `RecursionError` once the max recursion depth is exceeded. 

Here is a short example with copy.copy() triggering the recursion:
```
import copy, stix2
indicator = stix2.Indicator(name="a", labels=["a"], pattern="[file:name = 'a']")
copy.copy(indicator)
```

I believe this is because the unpickling tries to find the optional `__set_state__` method in `_STIXBase`. But since it's not there, the `__getattr__` is being called for it. However, the way `__getattr__` is implemented in the class, the `__getitem__` is called which  tries to look up an item in `self._inner`. Due to the way the deserialization works in general, the object itself is empty and the `__init__` was never called - meaning that the `_inner` attribute was never set. The access attempt on the non-existent `_inner` however triggers a call to `__getattr__` again, resulting in the recursion.

Here are two possible patches, I'm not sure though if that's the proper way of fixing it:

1) Checking for `_inner` access in `__getitem__`:
```
def __getitem__(self, key):
    if key == '_inner':
        raise KeyError
    return self._inner[key]

```
2) Checking for protected attributes in `__getattr__`:
```
def __getattr__(self, name):
    if name.startswith('_'):
        raise AttributeError(name)
    if name in self:
        return self.__getitem__(name)
    raise AttributeError("'%s' object has no attribute '%s'" %
                         (self.__class__.__name__, name))
```

Thanks!

**Comment by chisholm** [comment]
I was able to reproduce on both python2 and 3.  This was a surprise to me, but I guess \_\_getattr\_\_ is a "dangerous" method, in the presence of pickling.  But there is a note under the docs for [\_\_setstate\_\_](https://docs.python.org/3/library/pickle.html#object.__setstate__) (and similar for python2) that says as much.  And lists a couple other dangerous methods too.

So based on those docs, I'd put the fixes in \_\_setattr\_\_ and \_\_getattr\_\_.  Add an "is `self` initialized" check, which could be something like changing the "if" condition:

```python
if "_inner" in self.__dict__ and name in self:
    return self.__getitem__(name)
raise AttributeError("'%s' object has no attribute '%s'" %
                     (self.__class__.__name__, name))
```
The `"_inner" in self.__dict__` part is the new check.  This basically prevents pickle's \_\_setstate\_\_ lookup from blowing us up.  It made my simple test work anyway.

Docs don't describe \_\_getitem\_\_ as dangerous, so I wouldn't change that method.  (Because pickle apparently wouldn't call it directly.)  And preventing all access to any attribute which begins with underscore seems like a funny idiosyncrasy.  And not directly addressing the problem; it only works due to a quirk of the naming.

**Comment by chisholm** [comment]
Hmmm... maybe it doesn't make sense to modify \_\_setattr\_\_.  It can't be prevented from working even if \_\_init\_\_ hasn't been called, otherwise there would be no way to set attributes on a new object being unpickled.  I guess it would only make sense if the \_\_setattr\_\_ implementation requires initialization to have occurred first.  Ours doesn't reference _inner or any of the other attributes set by the constructor.  So... that method is okay I guess.

**Comment by gtback** [comment]
Another thing I briefly considered (though I don't know if it would help at all in this case) is moving some of the "initialization" from `__init__` to `__new__`. I don't know if that would help with pickling, though.

**Comment by mbastian1135** [comment]
I like Andy's approach to putting the `._inner` check in `__getattr__`. As long as the pickle API doesnt blow up for any Python versions, I think that is a good enough litmus test. The fix is lightweight and  also makes sense: we hijacked `__getitem__ `to only look in '._inner' thus we  should have to handle the case for when '._inner' doesnt exist yet.
