### ISSUE TITLE
STIX v2.0 UUIDs not accepted

### ISSUE THREAD

**Issue by Big4SMK** [oasis-open/cti-python-stix2#254]
With [this commit](https://github.com/oasis-open/cti-python-stix2/commit/a042970a1ff9dda3fc5929e362d4b3234bd79061#diff-66d4b16e89866438cb36e7eafa7ffa50), the UUID parsing was moved from using uuid.UUID() to a regex. That change led to the code no longer accepting valid STIXv2.0 UUID's, as the regex forces what is in the comment:

```
component must be a 4, and the first hex digit of the fourth component
# must be 8, 9, a, or b (10xx bit pattern)
```

However, that is not part of the STIXv2.0 spec, but only true for STIXv2.1. 
Thus example STIXv2.0 found at https://oasis-open.github.io/cti-documentation/examples/indicator-for-malicious-url is no longer deemed valid by the parser, even though it is.

**Comment by traut** [comment]
I would like to add that regex validation of UUIDs is a poor form. `uuid` library should be used

**Comment by StephenOTT** [comment]
Where is the docs on why the spec is moving away from stand UUID formats? 

Thanks

**Comment by jmgnc** [comment]
So, that's because it looks like at least one of the ids of the examples at https://oasis-open.github.io/cti-documentation/examples/indicator-for-malicious-url are not valid.

```
>>> a = 'd81f86b9-975b-bc0b-775e-810c5ad45a4f'
>>> u = uuid.UUID(a)
>>> u.variant
'reserved for NCS compatibility'
```

The docs for variant are (https://docs.python.org/3/library/uuid.html#uuid.UUID.variant):
> The UUID variant, which determines the internal layout of the UUID. This will be one of the constants > RESERVED_NCS, RFC_4122, RESERVED_MICROSOFT, or RESERVED_FUTURE.

and the variant is NOT RFC-4122, so therefor cannot be a version 4 as required by the 2.0 spec (https://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html):
> n identifier universally and uniquely identifies a SDO, SRO, Bundle, or Marking Definition. Identifiers MUST follow the form object-type--UUIDv4, where object-type is the exact value (all type names are lowercase strings, by definition) from the type property of the object being identified or referenced and where the UUIDv4 is an RFC 4122-compliant Version 4 UUID.

**Comment by emmanvg** [comment]
@Big4SMK, from a library standpoint I don't think there is any action. As @jmgnc mentioned, the UUID in some of those example objects are **not** valid Version 4 UUIDs and hence why it fails when parsing the https://oasis-open.github.io/cti-documentation/examples/indicator-for-malicious-url example. 

My recommendation is to open an issue on the documentation repo https://github.com/oasis-open/cti-documentation/issues so that the example gets updated. @traut, The Regular Expression currently present is able to successfully validate UUIDv4. However, we are always open to receiving contributions and help make the library more robust.

I am closing this issue, but feel free to re-open if you think your issue has not been resolved.

**Comment by clenk** [comment]
The examples on https://github.com/oasis-open/cti-documentation/ have been fixed. Thanks for bringing this up.
