### ISSUE TITLE
Patterns including backslash raise an error

### ISSUE THREAD

**Issue by yoyokoyo** [oasis-open/cti-python-stix2#260]
When creating an Indicator object with pattern keyword argument that include a backslash/double-backslash (like URLs or directory paths), for example :
```
"[file:parent_directory_ref.path = 'C:\Windows\System32']"
```
An invalid value error will raise, as in the following:
```
stix2.exceptions.InvalidValueError: Invalid value for Indicator 'pattern': FAIL: Error found at line 1:34. mismatched input ''' expecting {IntNegLiteral, IntPosLiteral, FloatNegLiteral, FloatPosLiteral, HexLiteral, BinaryLiteral, StringLiteral, BoolLiteral, TimestampLiteral}
```
Is editing the ANTLR4 grammar file the solution for this, or there is a better way to deal with it?
Thanks

**Comment by clenk** [comment]
Hi @yoyokoyo, backslashes in strings in STIX patterns must be escaped, like the examples in the patterning specification. `[file:parent_directory_ref.path = 'C:\\Windows\\System32']` passes the pattern validator. However, since this is Python, the backslashes must be escaped for Python as well.

So you could create an indicator with that pattern like so:
```
stix2.Indicator(labels=['anomalous-activity'], pattern="[file:parent_directory_ref.path = 'C:\\\\Windows\\\\System32']")
```

**Comment by yoyokoyo** [comment]
Thank you @clenk, it works better now. Have a great weekend!
