### ISSUE TITLE
How to list all campaigns - relationships

### ISSUE THREAD

**Issue by gtsafeB** [oasis-open/cti-python-stix2#266]
Hi,
I'd like to list all the campaigns and make a relationship between technique and campaign.
The question that I need to answer is: In technique which campaign used this technique?

**Comment by clenk** [comment]
Hi @gtsafeB. I assume by "technique" you mean "attack-pattern" (since that is how ATT&CK techniques are modeled in STIX); please correct me if that assumption is wrong.

You can find details on how to use the datastore to de-reference relationships here: [https://stix2.readthedocs.io/en/latest/guide/datastore.html#De-Referencing-Relationships](https://stix2.readthedocs.io/en/latest/guide/datastore.html#De-Referencing-Relationships)

To find which objects in the datastore used a specific attack-pattern you would do something like the following. If the attack-pattern was named `technique` and the datastore was a Memory datastore named `mem` you could do:
```python
mem.related_to(technique, target_only=True, relationship_type='uses')
```

To limit the results to just `campaign` objects you could add a filter:
```python
from stix2 import Filter

campaign_filter = Filter('type', '=', 'campaign')
mem.related_to(technique, target_only=True, relationship_type='uses', filters=[campaign_filter])
```

**Comment by gtsafeB** [comment]
Hi,
First, thank you for the quick reply.
"MemoryStore" is the same as using "FileSystemSource"? 
if not, what will be the syntax for the relation between "Campaign" to "attack-pattern"?

**Comment by clenk** [comment]
Yes, the method call would be the same for any DataStore or DataSource, including FileSystemSource.
