### ISSUE TITLE
Add SCOs to 2.1 objects mapping

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-python-stix2#298]
For STIX 2.1, we could add SCOs to the 2.1 `objects` mapping in `STIX2_OBJ_MAPS`. Since SCOs are now top level objects, this would allow `parse()` to handle both SDOs and SCOs without requiring use of `parse_observable()`.

**Comment by cobsec** [comment]
@clenk just wanted to lend a vote for this one - current implementation (that does not have SCO types included) results in the inability to create Bundles containing SCOs since it checks types on parse. I'm working around it at the moment by adding `_Observable` to the list of "no further checks" in the clean function of STIXObjectProperty:
https://github.com/oasis-open/cti-python-stix2/blob/d4c01157352552e2ec05bcf7b0f79ef96e34022d/stix2/properties.py#L627

**Comment by clenk** [comment]
This was fixed by #297.
