### ISSUE TITLE
version arg is not passed down with the call to parse in STIXObjectProperty.clean

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-python-stix2#318]
If the version argument is passed in on the original call to parse, it should be passed down also in any recursive calls.  This was not the case here: https://github.com/oasis-open/cti-python-stix2/blob/e3c2a3a57b83da8ce914ba7ea738d2e2813d551e/stix2/properties.py#L685.

**Comment by chisholm** [comment]
Is this a reaction to, or related to my comment [here](https://github.com/MAECProject/maec5-to-stix2-translator/blob/317aa3182b42e988b9d5055db0dccfe962c06a0e/maec2stix/translator.py#L150-L159), specifically regarding adding a `spec_version` property to SCOs?  I think I stumbled across this same thing, and decided it was not a bug.  The reason is because I thought STIX 2.1 bundles were allowed to contain both 2.0 and 2.1 objects.  That means it is inappropriate force a single version on the objects you add to it.

So 2.1 bundles must somehow figure out the spec version of each object individually.  spec_version is optional in STIX 2.1, and without it, there is no good way to identify object spec versions, which could be seen as a problem.  My solution was to add a spec_version property to all objects so that they were self-identifying.

How to detect spec version without a spec_version property wasn't in scope for the translator, so I did something simple.  Maybe it's a STIX spec issue?  Or maybe people just thought APIs should include spec version as separate metadata, and accepted that you wouldn't try to figure it out from a plain old STIX object dict?  Maybe we need to think about adjusting our stix2 library APIs to allow callers to specify spec version per-object, where necessary?  Or just tell people to add the spec_version property to help the library out, which is what I did?

**Comment by rpiazza** [comment]
No, I didn't see you comment - this was the result of a bug I came across while updating the slider.  You make a good point about a bundle containing both 2.0 and 2.1 objects.  I didn't look at the code in detail, @clenk and I just thought this would be an easy quick fix.  I guess the passed in version arg should be used as the "default" version, for when if the spec_version property isn't available.  On the other hand -  SCOs can only be 2.1 objects - in 2.0 cyber observables don't exist at the top-level.  Also, spec_version is only optional on SCOs, it is required for SDO/SROs

I guess we need to look into this more deeply. as you say.

**Comment by chisholm** [comment]
> On the other hand - SCOs can only be 2.1 objects

Yeah, but there was nothing in the stix2 "parsing" code to autodetect an object dict as a 2.1 SCO.  I looked, the code is very simple: if you don't specify a version and there is no spec_version property, there is a little bit of smarts regarding bundles, but aside from that, it assumes 2.0.  Obviously that doesn't work for a 2.1 SCO without a spec_version property.

>  Also, spec_version is only optional on SCOs, it is required for SDO/SROs

Ah, right.  I wanted to double-check that but access to google docs was blocked! /sighhh

**Comment by clenk** [comment]
Yes, `spec_version` is optional on SCOs. We could have `STIXObjectProperty.clean()` check if spec_version doesn't exist on the object but the object type is in STIX2_OBJ_MAPS['v21']['observables'] and if so use 2.1 as the spec_version. This would catch custom SCOs if the user's registered them, but would treat other custom SCOs as 2.0 SDOs.

Another option might be to just disallow bundles with mixed spec version content in `python-stix2.` I don't really like either of these options though.

**Comment by chisholm** [comment]
I think that ideally, `STIXObjectProperty.clean()` wouldn't do version detection.  The `parse()` function must do that to pick the right class, so anything similar put into clean() would be redundant.  (I realize there is a little check there now to prevent 2.1 objects getting into 2.0 bundles...)

I also don't think we necessarily assume 2.1, if `stix2.DEFAULT_VERSION` is "2.0".  If that's the default version, that should be our default assumption when there is ambiguity, I would think.  A type could be in both the v20 and v21 maps, so mere existence in the v21 map doesn't mean what you have is a v21 object.  If a type is in both maps as an SCO, and has no spec_version property, maybe presence of an `id` property could help?  In 2.0, IDs were external to SCOs.

**Comment by clenk** [comment]
The reason I suggested putting it in `STIXObjectProperty` is because it knows about the spec_version on the bundle (if present). but you're right, that doesn't actually help.

I was assuming 2.1 because 2.0 SCOs can't exist outside an `observed-data` object, but yeah checking both maps would be more complete.

So in parse, if `spec_version` is not in the object, and it's not a bundle, we have to look in the `observables` mappings for both `v20` and `v21` but start with whichever one is the `stix2.DEFAULT_VERSION` and if it's `2.0` also look in the `objects` mapping. Does that seem accurate?

**Comment by rpiazza** [comment]
I guess there is nothing in the spec that prevents you from having a custom SCO in 2.0, but I wonder if anyone has really thought about it - are there consequences of that feature we need to consider?

**Comment by rpiazza** [comment]
This text in the 2.0 spec might be relevant:

Custom Objects MUST support the Common Properties as defined in section 3.1. 
The definitions of these properties are the same as those defined in Common Properties and therefore those properties MUST NOT be used to represent the custom properties in the object.

 And section 3.1 refers only to SDO/SRO

So I think this means that no one envisioned custom SCOs in 2.0 - but it isn't explicitly prohibited

**Comment by chisholm** [comment]
@clenk : parse() has been changed to work for both observables (even 2.0) and SDOs/SROs right?  So the function needs to recognize all of those things.  (I see parse_observable() is still there though, so we'll have to ensure that works too.)  Thinking of a more detailed algorithm... yeah, if there is ambiguity, check the mappings for `stix2.DEFAULT_VERSION` first, then the "other" version.  But if we make use of IDs, maybe we won't (yet) have to deal with ambiguity.  Perhaps if there is no ID property, we conclude it must be a 2.0 SCO?  Otherwise, if a bundle { spec_version present=>2.0 else 2.1 }, else if spec_version present => 2.1, else no spec_version is present, so it could be a 2.1 SCO or 2.0 SDO/SRO.  Need to consult type maps.  If type is in the 2.1 SCO type map => 2.1, else 2.0?

@rpiazza : If the above strategy works, then custom 2.0 SCOs would be handled, right?  They wouldn't have an ID, so right away you know what they are.  Does that `parse()` method need to handle anything else that doesn't have an ID property?  (Of course, they'd have to be registered too, so we have a class in the appropriate mapping.)

**Comment by rpiazza** [comment]
@chisholm - you should be able to recognize 2.0 SCOs (if they even ever exist) as they MUST be wrapped in an Observable. So any top-level SCOs must be 2.1 . I don't know if this provides any help to fix the problem.  The ID issue is seems like a good idea to explore.

**Comment by clenk** [comment]
Related: https://github.com/oasis-tcs/cti-stix2/issues/217
