### ISSUE TITLE
A Custom Object in object_refs of a Report Object.

### ISSUE THREAD

**Issue by stmtstk** [oasis-open/cti-python-stix2#333]
Hi,

I appended a custom object ref in object_refs of a Report object and wrote into a file.
However stix2 library can not parse the stix2 file.

I checked the source code and found the line below.

` ('object_refs', ListProperty(ReferenceProperty(valid_types=["SCO", "SDO", "SRO"], spec_version='2.1'), required=True)),
`
It seems that an object_refs property allows to contain only  "SCO", "SDO", "SRO", but a custom object does not realized as those.

Is is the right behavior? 
Or is a Custom Object setting wrong?

If you have any idea, please let me know.

Thank you!

**Comment by stmtstk** [comment]
I found the sentence in STIX2 specification document.

> Relationships are not restricted to those listed below. Relationships can be created between any objects using the related-to relationship name or, as with open vocabularies, user-defined names.

I think that an object_refs should support user-defined names like a CustomObject.

**Comment by clenk** [comment]
Hi @stmtstk thanks for the question. Yes, you should be able to add custom objects to that property.

We will work to add an option to allow custom objects to reference properties, but in the meantime, have you tried defining your CustomObject as described [here in our documentation](https://stix2.readthedocs.io/en/latest/guide/custom.html#Custom-STIX-Object-Types)? That won't work for every case since you may not know ahead of time what custom object types you will receive, but if you do then it should work.

**Comment by stmtstk** [comment]
Thank you for a kindly reply!

Off course, I defined a CustomObject properties by using the @CustomObject decorator.
I generated a CustomObject instance, and tried to append the instance id into an object_refs property in Report Object. But it failed because of an invalid types.

Is it a right use?

**Comment by stmtstk** [comment]
I added my CustomObject decorator block in a python script which contains stix.parse and parse finished successfully.

Thank you!

I am looking forward to add an allow_custom option.

**Comment by clenk** [comment]
This should now be fixed in #503.
