### ISSUE TITLE
Stix 2.1

### ISSUE THREAD

**Issue by jbfeldman** [oasis-open/cti-python-stix2#387]
Hi all,

I have the latest version of stix2 but it's still generating STIX 2.0 instead of 2.1: Indicators have to have labels, spec is 2.0, etc. I've been looking through the issue and I see that 2.0 is still the default, but is there a way to force adherence to 2.1? I haven't been able to find anything in the documentation about it

**Comment by emmanvg** [comment]
@jbfeldman I think the documentation provides enough examples on how to import objects relevant to the specification of STIX you are looking.

- For instance: https://stix2.readthedocs.io/en/latest/guide/ts_support.html talks about how the import statement works for this library. As mentioned on issues #380, #381 the last changes before making the next major release will be to load 2.1 objects by default. A potential backwards breaking change if the code was not written with adherence to a specific version. Keep in mind, this does not prevent you from using 2.1 on the latest current version (v1.4.0) as of this writing.

- There has been a note on the repo [README](https://github.com/oasis-open/cti-python-stix2#stix-2x-technical-specification-support) about why 2.0 objects are still the default loaded ones.

You could try:

``` python
from stix2.v21 import Indicator

indicator = Indicator(
    indicator_types=['malicious-activity'],
    pattern='[file:hashes.MD5 = "d41d8cd98f00b204e9800998ecf8427e"]',
    pattern_type="stix",
    valid_from="2017-01-01T12:34:56Z",
)
```
OR
``` python
from stix2 import v21

indicator = v21.Indicator(
    indicator_types=['malicious-activity'],
    pattern='[file:hashes.MD5 = "d41d8cd98f00b204e9800998ecf8427e"]',
    pattern_type="stix",
    valid_from="2017-01-01T12:34:56Z",
)
```

Closing since answer to this question already exists. If you feel your question has not been addressed feel free to reopen.
