### ISSUE TITLE
ModuleNotFoundError: No module named 'six.moves.collections_ab

### ISSUE THREAD

**Issue by Lastrellik** [oasis-open/cti-python-stix2#425]
With version 2.02 I get this `ModuleNotFoundError: No module named 'six.moves.collections_ab` error when trying to run any of our stix scripts, for one example:
```python
from stix2.v20 import EmailMIMEComponent, Artifact, File

attachment_type = 'application/pdf'
attachment_binary = b'ZW1haWwgYXR0YWNobWVudCBjb250ZW50cwo='
hashes = {
    'MD5': 'ffa4344d434659d6fc69eca166f870a7',
    'SHA1': '0e518dcead742e7127345d15ca7eba694b50d0fa'
}
artifact = Artifact(hashes=hashes, payload_bin=attachment_binary, mime_type=attachment_type)

email_mime_component_attachment = EmailMIMEComponent(
    body_raw_ref="0"  
)

print(email_mime_component_attachment)

```
This happens both after upgrading to 2.02 and with a clean install of stix2 on a fresh virtual enviornment.

**Comment by emmanvg** [comment]
Hi @Lastrellik! this issue has been resolved on version `2.0.2` of the library. I tested locally (see attachment) and was able to run the script without problems. If you update via PyPI it should have updated your `six` dependency to something higher or equal to `1.13.0`. Another suggestion would be to check your `pip`, `setuptools` and `wheel` packages are up-to-date on your environment. I will close this since we think it has been resolved. 

duplicate #422 
![Annotation 2020-07-08 133154](https://user-images.githubusercontent.com/8574582/86951360-6b813c00-c11f-11ea-99a8-b43a2393ce74.jpg)
