### ISSUE TITLE
Access tactics of MITRE TaxiiServer results in AttributeError exception

### ISSUE THREAD

**Issue by Eiwanger** [oasis-open/cti-python-stix2#459]
Hello,

while I tried to test the examples on [mitre/cti](https://github.com/mitre/cti/blob/master/USAGE.md) I got an Error with the function `getTacticsByMatrix()` (https://github.com/mitre/cti/blob/master/USAGE.md#tactics-by-matrix). The exception `(<class 'AttributeError'>, AttributeError("'dict' object has no attribute 'id'"), <traceback object at 0x0000018701634CC8>)` is thrown in [taxii.py](https://github.com/mitre/cti/blob/master/USAGE.md#tactics-by-matrix) in `def get(self, stix_id, version=None, _composite_filters=None)` in line 213.  The `parse()` function returns the dict if it is not able to parse it into a STIX object. Therefore if the parse fails it will alway result in an exception. 

Is this behaviour intentional?

**Comment by emmanvg** [comment]
Hi @Eiwanger, thanks for spotting this issue. It is not intentional behavior, when `stix2` tries to parse unregistered custom objects it defaults to returning a dictionary instance. The code was doing a attribute access which is only possible for registered objects. The fix will be available in the next release.
