### ISSUE TITLE
Which is the proper way to store and retrieve STIX bundles

### ISSUE THREAD

**Issue by asdimitriadis** [oasis-open/cti-python-stix2#494]
My question is related to storing STIX bundles in a NoSQL database like mongoDB.

Let's assume that we receive a CTI feed from an organization in STIX format. The organization send us a STIX bundle that contains:
1. An Identity SDO
2. An Indicator SDO
3. A Relationship SRO that links Identity and Indicator with type = "targets"

We have a mongoDB and we want to store this STIX bundle. The solutions are two:
1. Store the whole bundle as is.
2. Store the Identity SDO, Indicator SDO and Relationship SRO in different collections (or in the same collection but in different entries)

The drawback of the first solution is that if we want to get the Indicator SDO to use it, we have to parse the whole STIX bundle.

The drawback of the second solution is that if we want to create the bundle again (e.g., to send it to someone else) we have to parse the Relationship SRO and then to find the Identity SDO and Indicator SDO using the source_ref and the target_ref.

Can you please help me which is the recommended way of storing STIX bundles in a mongoDB?

P.S. I apologize if I posted the question in the wrong place. Please let me know where I should post it.

**Comment by clenk** [comment]
In STIX 2 bundles are considered transient rather than permanent, and aren't considered to have any any semantic meaning. So I think the second solution more closely aligns with the STIX 2 specification. Storing the individual objects rather than the bundle as a whole also allows you to include any additional related objects you might receive in the future. For example, if some time after receiving the first bundle you receive a second bundle with a Sighting that refers to the Indicator in the first one, then when you want to send the information to someone else you could also include the Sighting.

Thanks for the question. For questions about STIX in general that aren't necessarily about the python library, a good place to ask them is the OASIS CTI Users mailing list: cti-users@lists.oasis-open.org.
