### ISSUE TITLE
is labels optional

### ISSUE THREAD

**Issue by workingDog** [oasis-open/cti-python-stix2#9]
Hi,
As an exercise I'm starting a similar Scala library for STIX 2.1, at:

   [scalastix]( https://github.com/workingDog/scalastix)

According to the specs and as part of the common properties, labels is optional.
However, there are SDOs (e.g. Indicator) where it is required. Is this correct?
labels are optional but not when required!

I see that labels are not part of the python COMMON_PROPERTIES.
Should I do the same?

**Comment by clenk** [comment]
That is correct. The labels property is optional by default, but for a couple SDOs it is required. We did not put it in COMMON_PROPERTIES so that we can set it differently for the SDOs in which it is required. However it looks like we forgot to add it to some of the SDOs. Thank you for pointing this out; we'll get it fixed.

I think it makes more sense to add it to COMMON_PROPERTIES and then have the SDOs that need to, like Indicator, overwrite it.

**Comment by gtback** [comment]
We didn't put `type` and `id` in COMMON _PROPERTIES because those really *are* different for every SDO, but for `labels` I agree it makes sense to have a "default" implementation in COMMON_PROPERTIES and restrict it where needed.
